### Numpy ndarray

In [1]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 shape:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 shape:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [7]:
print('array1: %d dimension, array2: %d dimension, array3: %d dimension' 
      %(array1.ndim, array2.ndim, array3.ndim))

array1: 1 dimension, array2: 2 dimension, array3: 2 dimension


In [11]:
print('array1: {:0} dimension, array2: {:1} dimension, array3: {:2} dimension'.format(
    array1.ndim,array2.ndim,array3.ndim))

array1: 1 dimension, array2: 2 dimension, array3:  2 dimension


In [14]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [16]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [23]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int8')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int8


### arange, zeros, ones

In [25]:
#arange, zeros, ones
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [28]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [33]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [35]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [40]:
array1 = np.arange(8)
print('array1:\n', array1.tolist())

array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3d -> 2d
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())

#1d -> 2d
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())

array1:
 [0, 1, 2, 3, 4, 5, 6, 7]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]


### indexing

- single value extraction

In [41]:
#1~9 1d ndarray
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [43]:
print('last value:', array1[-1], ', second most right value', array1[-2])

last value: 9 , second most right value 8


In [44]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [47]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print('(row=0,col=0):', array2d[0,0])
print('(row=0,col=1):', array2d[0,1])
print('(row=1,col=0):', array2d[1,0])
print('(row=2,col=2):', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0): 1
(row=0,col=1): 2
(row=1,col=0): 4
(row=2,col=2): 9


In [50]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [56]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)
print('array2d[0:2, 0:2]\n', array2d[0:2,0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3,0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:,:]\n', array2d[:,:])
print('array2d[:2,0]\n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,0]
 [1 4]


In [57]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


- Fancy indexing

In [61]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


- boolean indexing

In [62]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d>5]
print('array1d>5 boolean indexing:', array3)

array1d>5 boolean indexing: [6 7 8 9]


In [63]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

### Matrixing sorting -sort(), argsort()

In [67]:
org_array = np.array([3,1,9,5])
print('original array:', org_array)

#np.sort()
sort_array1 = np.sort(org_array)
print('returned sorted array:', sort_array1)
print('original array after sorting:', org_array)

#ndarray.sort()
sort_array2 = org_array.sort()
print('returned sorted array:', sort_array2)
print('original array after sorting:', org_array)

original array: [3 1 9 5]
returned sorted array: [1 3 5 9]
original array after sorting: [3 1 9 5]
returned sorted array: None
original array after sorting: [1 3 5 9]


In [70]:
# descending
sort_array1_desc = np.sort(org_array)[::-1]
print('descending order:', sort_array1_desc)

descending order: [9 5 3 1]


In [86]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('axis=0 sorting:\n', sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('axis=1 sorting:\n', sort_array2d_axis1)

axis=0 sorting:
 [[ 7  1]
 [ 8 12]]
axis=1 sorting:
 [[ 8 12]
 [ 1  7]]


- Returning index of the sorted array

In [88]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('index of original array:', sort_indices)

<class 'numpy.ndarray'>
index of original array: [1 0 3 2]


In [89]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('index of original array (descending):', sort_indices_desc)

index of original array (descending): [2 3 0 1]


In [90]:
import numpy as np
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)

print('index of score_array (ascending)', sort_indices_asc)
print('printing name in name array (ascending)', name_array[sort_indices_asc])

index of score_array (ascending) [0 2 4 1 3]
printing name in name array (ascending) ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### linear algebra calculation - inner product and transpose

In [95]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A,B)
dot_product1 = A@B
print('np.dot:\n',dot_product)
print('@:\n',dot_product1)      


np.dot:
 [[ 58  64]
 [139 154]]
@:
 [[ 58  64]
 [139 154]]


In [98]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
transpose_mat1 = A.T
print('np.transpose:\n', transpose_mat)
print('ndarray.T:\n', transpose_mat1)

np.transpose:
 [[1 3]
 [2 4]]
ndarray.T:
 [[1 3]
 [2 4]]
